//! Repository layer — the ONLY place that touches the `identity` schema.
//!
//! Runtime `sqlx::query`/`query_as` (not the compile-time `query!` macro): the scaffold
//! has no DATABASE_URL / offline `.sqlx` cache at build time. Argon2 work (CPU-bound) is
//! offloaded to `spawn_blocking` here — the scheduling is an I/O concern, so it lives in
//! `repo`, while the pure hash/verify functions stay in `domain::password`.

use std::sync::LazyLock;

use chrono::{DateTime, TimeDelta, Utc};
use sqlx::PgPool;
use uuid::Uuid;

use shared::error::AppError;

use crate::domain::rotation::StoredRefresh;
use crate::domain::{password, revocation};
use crate::models::AuthUserRow;

/// Refresh-token lifetime (RFC 6749 §6 rotation; 7 days mirrors v1).
const REFRESH_TOKEN_DAYS: i64 = 7;

/// A real Argon2id hash of a throwaway value, computed once at first use. Verified against
/// on the no-such-user / inactive path so login takes ~the same time whether or not the
/// account exists (anti-enumeration; ported from v1 auth `service.rs`). Generated by our
/// own hasher, so it is ALWAYS a valid PHC string — the no-user path can never 500 on a
/// hash-parse error (a hand-written constant could).
static DUMMY_HASH: LazyLock<String> =
    LazyLock::new(|| password::hash_secret("pguard-anti-enumeration-dummy").expect("dummy hash"));

/// Row returned by the login lookup (password hash stays inside repo).
struct UserAuthRow {
    id: Uuid,
    role: String,
    password_hash: String,
    is_active: bool,
    /// Account approval state (`pending`/`approved`/`rejected`). Login is allowed ONLY
    /// when `approved` — a registered-but-unapproved account cannot authenticate.
    approval_status: String,
    token_revocation_version: i32,
}

/// Look up a user by phone OR email. Returns `None` if absent (inactive users still
/// return so the caller can run the dummy-verify path uniformly).
async fn find_user_by_identifier(
    db: &PgPool,
    identifier: &str,
) -> Result<Option<UserAuthRow>, AppError> {
    let row: Option<(Uuid, String, String, bool, String, i32)> = sqlx::query_as(
        r#"
        SELECT id, role::text AS role, password_hash, is_active,
               approval_status::text AS approval_status, token_revocation_version
        FROM identity.users
        WHERE phone = $1 OR email = $1
        "#,
    )
    .bind(identifier)
    .fetch_optional(db)
    .await?;

    Ok(row.map(
        |(id, role, password_hash, is_active, approval_status, trv)| UserAuthRow {
            id,
            role,
            password_hash,
            is_active,
            approval_status,
            token_revocation_version: trv,
        },
    ))
}

/// Verify credentials. Always returns a generic `Unauthorized` on any failure (no
/// user-enumeration); runs the Argon2 verify even when the user is missing/ineligible so
/// timing does not leak existence OR approval state. Returns the minimal user identity on
/// success. ELIGIBILITY = active AND `approval_status = 'approved'`: a pending/rejected
/// account is rejected with the SAME generic 401 as a wrong password (so login cannot be
/// used to probe whether a phone is registered-but-pending).
pub async fn verify_credentials(
    db: &PgPool,
    identifier: &str,
    password: &str,
) -> Result<AuthUserRow, AppError> {
    let user = find_user_by_identifier(db, identifier).await?;

    // Pick the hash to verify against: the real one (only for an eligible account), or a
    // constant dummy. Either way we spend the same Argon2 time.
    let (hash, eligible, identity) = match &user {
        Some(u) if u.is_active && u.approval_status == "approved" => (
            u.password_hash.clone(),
            true,
            Some(AuthUserRow {
                id: u.id,
                role: u.role.clone(),
                token_revocation_version: u.token_revocation_version,
            }),
        ),
        _ => (DUMMY_HASH.to_string(), false, None),
    };

    let password = password.to_string();
    let ok = tokio::task::spawn_blocking(move || password::verify_secret(&password, &hash))
        .await
        .map_err(|e| AppError::Internal(format!("verify task failed: {e}")))??;

    match (ok, eligible, identity) {
        (true, true, Some(id)) => Ok(id),
        _ => Err(AppError::Unauthorized("Invalid credentials".to_string())),
    }
}

/// UPSERT a freshly-registered account in the `pending` (non-loginable) state and return
/// its `user_id`. The PIN-hash supplied by the client (SHA-256 hex of the PIN) is Argon2'd
/// here (CPU-bound → `spawn_blocking`) and stored as the password hash.
///
/// `ON CONFLICT (phone)`: re-registering a phone that is STILL pending is allowed — it
/// refreshes the credentials/role and keeps the account pending (a user who never finished
/// onboarding can start over). A phone that already exists in a NON-pending state
/// (approved/rejected) makes the `WHERE approval_status = 'pending'` predicate false, so the
/// row is NOT touched and `RETURNING` yields no row → `Conflict` ("log in instead"). This is
/// the only place identity creates a user; profile/otp never write this schema.
// `skip(db, phone, pin_hash)`: never log the phone (PII) or the pin hash; `role` is fine.
#[tracing::instrument(skip(db, phone, pin_hash))]
pub async fn upsert_pending_user(
    db: &PgPool,
    phone: &str,
    role: &str,
    pin_hash: &str,
) -> Result<Uuid, AppError> {
    let pin_hash = pin_hash.to_string();
    let password_hash = tokio::task::spawn_blocking(move || password::hash_secret(&pin_hash))
        .await
        .map_err(|e| AppError::Internal(format!("hash task failed: {e}")))??;

    let row: Option<(Uuid,)> = sqlx::query_as(
        r#"
        INSERT INTO identity.users (phone, password_hash, role, approval_status)
        VALUES ($1, $2, $3::identity.user_role, 'pending'::identity.approval_status)
        ON CONFLICT (phone) DO UPDATE
          SET password_hash   = EXCLUDED.password_hash,
              role            = EXCLUDED.role,
              approval_status = 'pending'::identity.approval_status,
              updated_at      = now()
          WHERE identity.users.approval_status = 'pending'::identity.approval_status
        RETURNING id
        "#,
    )
    .bind(phone)
    .bind(&password_hash)
    .bind(role)
    .fetch_optional(db)
    .await?;

    row.map(|(id,)| id).ok_or_else(|| {
        AppError::Conflict(
            "This phone number is already registered. Please log in instead.".to_string(),
        )
    })
}

/// Switch a PENDING account's role (the onboarding "pick another role" path). Pending accounts
/// only — a non-pending row is left untouched and the caller gets a Conflict ("log in instead"),
/// mirroring [`upsert_pending_user`]. No password/phone change.
pub async fn update_pending_user_role(
    db: &PgPool,
    user_id: Uuid,
    role: &str,
) -> Result<(), AppError> {
    let res = sqlx::query(
        r#"
        UPDATE identity.users
           SET role = $2::identity.user_role,
               updated_at = now()
         WHERE id = $1
           AND approval_status = 'pending'::identity.approval_status
        "#,
    )
    .bind(user_id)
    .bind(role)
    .execute(db)
    .await?;

    if res.rows_affected() == 0 {
        return Err(AppError::Conflict(
            "This account can no longer change role. Please log in instead.".to_string(),
        ));
    }
    Ok(())
}

/// Outcome of consuming a `user.approved` event.
#[derive(Debug, PartialEq, Eq)]
pub enum ApprovedOutcome {
    /// The account was flipped to `approved` (it can now log in).
    Applied,
    /// This `event_id` was already processed — a redelivery; no-op (idempotent).
    Duplicate,
    /// No such user (or already deleted). The event is still recorded as processed so it does
    /// not redeliver forever; logged by the caller.
    UserNotFound,
}

/// Flip the user's OWN `approval_status` to `approved`, driven by the `user.approved` event
/// that profile emits on admin approval. **Idempotent by `event_id`**: the claim into
/// `processed_events` + the `users` update happen in ONE transaction, so a redelivered event
/// (JetStream at-least-once) is a safe no-op. This is identity writing its OWN schema — the
/// event is the only coupling to profile (no cross-schema write in either direction).
#[tracing::instrument(skip(db), fields(event_id = %event_id, user_id = %user_id))]
pub async fn approve_user_on_event(
    db: &PgPool,
    event_id: Uuid,
    event_type: &str,
    user_id: Uuid,
) -> Result<ApprovedOutcome, AppError> {
    let mut tx = db.begin().await?;

    // 1) Claim the event_id — the idempotency anchor. A redelivery inserts nothing.
    let claim = sqlx::query(
        "INSERT INTO identity.processed_events (event_id, event_type) \
         VALUES ($1, $2) ON CONFLICT (event_id) DO NOTHING",
    )
    .bind(event_id)
    .bind(event_type)
    .execute(&mut *tx)
    .await?;
    if claim.rows_affected() == 0 {
        tx.rollback().await?;
        return Ok(ApprovedOutcome::Duplicate);
    }

    // 2) Flip approval_status. Only a live (not soft-deleted) account is approvable — so a
    //    stale/forged approval can never re-enable an erased account (login also re-checks
    //    is_active independently, defense-in-depth).
    let res = sqlx::query(
        "UPDATE identity.users \
         SET approval_status = 'approved'::identity.approval_status, updated_at = now() \
         WHERE id = $1 AND deleted_at IS NULL",
    )
    .bind(user_id)
    .execute(&mut *tx)
    .await?;

    // Commit the claim even when 0 rows matched (UserNotFound). This is deliberate: in the real
    // flow the identity row ALWAYS predates an approval (register → profile submit → admin
    // approve, each gated on the prior), so a 0-row match means a forged/stale/deleted-user
    // event — recording it (vs. rollback) prevents a bogus event from redelivering forever. The
    // caller logs UserNotFound loudly so a genuine anomaly is still visible.
    tx.commit().await?;

    if res.rows_affected() == 0 {
        Ok(ApprovedOutcome::UserNotFound)
    } else {
        Ok(ApprovedOutcome::Applied)
    }
}

/// Max concurrent live refresh families (≈ logged-in sessions) per user. A new login beyond
/// this evicts the least-recently-active family, so a login loop / token-minting abuse cannot
/// grow unbounded session state (the only other ceiling is natural 7-day expiry).
const MAX_SESSIONS_PER_USER: i64 = 5;

/// Persist a freshly-issued refresh token (new family on login). Returns the opaque
/// token the client receives (`{rotation_id}.{secret}`). Enforces the per-user session cap
/// first (evict oldest beyond the cap).
pub async fn create_refresh_family(db: &PgPool, user_id: Uuid) -> Result<String, AppError> {
    enforce_session_cap(db, user_id).await?;
    let family_id = Uuid::new_v4();
    issue_refresh(db, user_id, family_id).await
}

/// Revoke the least-recently-active refresh families beyond `MAX_SESSIONS_PER_USER - 1`, so that
/// after the caller adds the new family the user ends at most at the cap. "Recency" is the
/// family's most recent rotation (`MAX(created_at)`), i.e. LRU eviction. (A rare concurrent-login
/// race may transiently leave cap+1 families; it self-corrects on the next login and is a
/// hardening control, not a hard invariant — so we don't pay for a serializing lock here.)
async fn enforce_session_cap(db: &PgPool, user_id: Uuid) -> Result<(), AppError> {
    let stale: Vec<(Uuid,)> = sqlx::query_as(
        r#"
        SELECT family_id FROM (
            SELECT family_id, MAX(created_at) AS last_active
            FROM identity.refresh_tokens
            WHERE user_id = $1 AND revoked = FALSE
            GROUP BY family_id
            ORDER BY last_active DESC
            OFFSET $2
        ) evictable
        "#,
    )
    .bind(user_id)
    .bind(MAX_SESSIONS_PER_USER - 1)
    .fetch_all(db)
    .await?;

    for (family_id,) in stale {
        revoke_family(db, family_id).await?;
    }
    Ok(())
}

/// Insert one refresh-token row in `family_id` and return its opaque token. Used for the
/// initial login token (rotation uses its own in-tx insert).
async fn issue_refresh(db: &PgPool, user_id: Uuid, family_id: Uuid) -> Result<String, AppError> {
    let rotation_id = Uuid::new_v4();
    let jti = Uuid::new_v4();
    let secret = Uuid::new_v4().to_string();
    let expires_at: DateTime<Utc> = Utc::now() + TimeDelta::days(REFRESH_TOKEN_DAYS);

    let secret_for_hash = secret.clone();
    let secret_hash = tokio::task::spawn_blocking(move || password::hash_secret(&secret_for_hash))
        .await
        .map_err(|e| AppError::Internal(format!("hash task failed: {e}")))??;

    sqlx::query(
        r#"
        INSERT INTO identity.refresh_tokens
            (user_id, family_id, rotation_id, jti, secret_hash, expires_at)
        VALUES ($1, $2, $3, $4, $5, $6)
        "#,
    )
    .bind(user_id)
    .bind(family_id)
    .bind(rotation_id)
    .bind(jti)
    .bind(&secret_hash)
    .bind(expires_at)
    .execute(db)
    .await?;

    Ok(crate::domain::token::assemble(rotation_id, &secret))
}

/// A refresh row located by its `rotation_id`, with everything the rotation decision +
/// secret check need.
pub struct LocatedRefresh {
    pub user_id: Uuid,
    pub family_id: Uuid,
    /// Rotation-decision inputs (revoked/expiry/family age) — the family-age ceiling now lives in
    /// `StoredRefresh::family_started_at` so `domain::rotation::decide` owns the whole decision.
    pub stored: StoredRefresh,
    secret_hash: String,
}

impl LocatedRefresh {
    /// Argon2-verify the presented secret against the stored hash (constant-time).
    pub async fn secret_matches(&self, secret: &str) -> Result<bool, AppError> {
        let secret = secret.to_string();
        let hash = self.secret_hash.clone();
        tokio::task::spawn_blocking(move || password::verify_secret(&secret, &hash))
            .await
            .map_err(|e| AppError::Internal(format!("verify task failed: {e}")))?
    }
}

/// Locate a refresh-token row by its public `rotation_id`.
// The row tuple gains a 6th column (family_started_at) for the absolute-rotation ceiling; the
// file consistently uses positional tuples for ad-hoc row reads, so allow the wider shape here.
#[allow(clippy::type_complexity)]
pub async fn find_refresh_by_rotation(
    db: &PgPool,
    rotation_id: Uuid,
) -> Result<Option<LocatedRefresh>, AppError> {
    let row: Option<(Uuid, Uuid, bool, DateTime<Utc>, DateTime<Utc>, String)> = sqlx::query_as(
        r#"
        SELECT rt.user_id, rt.family_id, rt.revoked, rt.expires_at,
               (SELECT MIN(created_at) FROM identity.refresh_tokens f
                WHERE f.family_id = rt.family_id) AS family_started_at,
               rt.secret_hash
        FROM identity.refresh_tokens rt
        WHERE rt.rotation_id = $1
        "#,
    )
    .bind(rotation_id)
    .fetch_optional(db)
    .await?;

    Ok(row.map(
        |(user_id, family_id, revoked, expires_at, family_started_at, secret_hash)| {
            LocatedRefresh {
                user_id,
                family_id,
                stored: StoredRefresh {
                    revoked,
                    expires_at,
                    family_started_at,
                },
                secret_hash,
            }
        },
    ))
}

/// Atomically revoke the presented rotation and mint its successor in the SAME family.
/// One transaction: prevents a window where the old token is dead but the new one is not
/// yet recorded (RFC 6749 §6 rotation).
///
/// Returns `Ok(None)` when the presented rotation was ALREADY revoked by the time the
/// conditional UPDATE ran — i.e. a concurrent refresh of the very same token (double-spend
/// race) won the row first. In that case we mint NO successor, so one refresh token can never
/// yield two live chains; the caller rejects the loser with 401.
pub async fn rotate(
    db: &PgPool,
    user_id: Uuid,
    family_id: Uuid,
    presented_rotation_id: Uuid,
) -> Result<Option<String>, AppError> {
    let mut tx = db.begin().await?;

    // Conditional revoke: only the FIRST rotation of this token flips revoked false→true and
    // affects a row. A concurrent second rotation sees 0 rows and must abort (no successor).
    let revoked = sqlx::query(
        "UPDATE identity.refresh_tokens SET revoked = TRUE WHERE rotation_id = $1 AND revoked = FALSE",
    )
    .bind(presented_rotation_id)
    .execute(&mut *tx)
    .await?;
    if revoked.rows_affected() == 0 {
        tx.rollback().await?;
        return Ok(None);
    }

    // Re-issue inside the family. We hash + insert here rather than calling `issue_refresh`
    // so the whole rotate stays in one tx.
    let rotation_id = Uuid::new_v4();
    let jti = Uuid::new_v4();
    let secret = Uuid::new_v4().to_string();
    let expires_at: DateTime<Utc> = Utc::now() + TimeDelta::days(REFRESH_TOKEN_DAYS);
    let secret_for_hash = secret.clone();
    let secret_hash = tokio::task::spawn_blocking(move || password::hash_secret(&secret_for_hash))
        .await
        .map_err(|e| AppError::Internal(format!("hash task failed: {e}")))??;

    sqlx::query(
        r#"
        INSERT INTO identity.refresh_tokens
            (user_id, family_id, rotation_id, jti, secret_hash, expires_at)
        VALUES ($1, $2, $3, $4, $5, $6)
        "#,
    )
    .bind(user_id)
    .bind(family_id)
    .bind(rotation_id)
    .bind(jti)
    .bind(&secret_hash)
    .bind(expires_at)
    .execute(&mut *tx)
    .await?;

    tx.commit().await?;

    Ok(Some(crate::domain::token::assemble(rotation_id, &secret)))
}

/// Revoke every token in a family (logout, or reuse-detection kill-switch).
pub async fn revoke_family(db: &PgPool, family_id: Uuid) -> Result<u64, AppError> {
    let res = sqlx::query(
        "UPDATE identity.refresh_tokens SET revoked = TRUE WHERE family_id = $1 AND revoked = FALSE",
    )
    .bind(family_id)
    .execute(db)
    .await?;
    Ok(res.rows_affected())
}

/// The user's current role (re-read at rotation so a role change since login is honoured
/// in the freshly-issued access token). `None` if the user is gone, deactivated, or no
/// longer approved — so a refresh cannot mint a fresh access token for an account that has
/// become pending/rejected since login (defense-in-depth; a pending account never had a
/// refresh token to begin with).
pub async fn user_auth_meta(db: &PgPool, user_id: Uuid) -> Result<Option<AuthUserRow>, AppError> {
    let row: Option<(String, i32)> = sqlx::query_as(
        r#"
        SELECT role::text AS role, token_revocation_version
        FROM identity.users
        WHERE id = $1 AND is_active = TRUE
          AND approval_status = 'approved'::identity.approval_status
        "#,
    )
    .bind(user_id)
    .fetch_optional(db)
    .await?;

    Ok(row.map(|(role, trv)| AuthUserRow {
        id: user_id,
        role,
        token_revocation_version: trv,
    }))
}

/// Force-revoke-all for a user: bump `token_revocation_version` AND revoke every
/// outstanding refresh family — in one transaction (CLAUDE.md "Token revocation").
/// Returns the new version. Idempotent enough for at-least-once event delivery.
#[tracing::instrument(skip(db), fields(user_id = %user_id))]
pub async fn revoke_all(db: &PgPool, user_id: Uuid) -> Result<i32, AppError> {
    let mut tx = db.begin().await?;

    // Read-modify-write under the tx (row locked) so the monotonic bump is computed by the
    // single domain helper rather than duplicated in SQL.
    let current: Option<(i32,)> = sqlx::query_as(
        "SELECT token_revocation_version FROM identity.users WHERE id = $1 FOR UPDATE",
    )
    .bind(user_id)
    .fetch_optional(&mut *tx)
    .await?;

    let current = match current {
        Some((v,)) => v,
        None => {
            tx.rollback().await?;
            return Err(AppError::NotFound("User not found".to_string()));
        }
    };
    let new_version = revocation::next_revocation_version(current);

    sqlx::query(
        r#"
        UPDATE identity.users
        SET token_revocation_version = $2, updated_at = now()
        WHERE id = $1
        "#,
    )
    .bind(user_id)
    .bind(new_version)
    .execute(&mut *tx)
    .await?;

    sqlx::query(
        "UPDATE identity.refresh_tokens SET revoked = TRUE WHERE user_id = $1 AND revoked = FALSE",
    )
    .bind(user_id)
    .execute(&mut *tx)
    .await?;

    tx.commit().await?;

    // Invariant: every access token stamped with the OLD version must now be rejected by a
    // version-checking validator. Cheap self-check on the security-critical path.
    debug_assert!(
        !revocation::token_version_is_current(current, new_version),
        "force-revoke-all must invalidate old-version tokens"
    );
    tracing::info!(new_version, "force-revoke-all applied");
    Ok(new_version)
}

/// PDPA §33 erasure: soft-delete the user in ONE tx — redact PII (phone → opaque
/// placeholder, email → NULL), deactivate (which blocks re-login via the `is_active` check
/// in [`verify_credentials`], and the original phone/email no longer match anyway), stamp
/// `deleted_at` (minimal retained audit), and force-revoke every token (bump `trv` + revoke
/// refresh families). Returns the new `trv` so the caller can publish the Redis marker that
/// rejects outstanding access tokens at once. Idempotent: an already-deleted user → NotFound.
#[tracing::instrument(skip(db), fields(user_id = %user_id))]
pub async fn soft_delete_and_redact(db: &PgPool, user_id: Uuid) -> Result<i32, AppError> {
    let mut tx = db.begin().await?;

    let current: Option<(i32,)> = sqlx::query_as(
        "SELECT token_revocation_version FROM identity.users \
         WHERE id = $1 AND deleted_at IS NULL FOR UPDATE",
    )
    .bind(user_id)
    .fetch_optional(&mut *tx)
    .await?;
    let current = match current {
        Some((v,)) => v,
        None => {
            tx.rollback().await?;
            return Err(AppError::NotFound(
                "User not found or already deleted".to_string(),
            ));
        }
    };
    let new_version = revocation::next_revocation_version(current);

    // Redact PII. `phone` is UNIQUE NOT NULL → an opaque per-user placeholder keeps the
    // constraint while carrying no personal data; `email` (UNIQUE, nullable) → NULL.
    sqlx::query(
        r#"
        UPDATE identity.users
        SET phone = $2, email = NULL, is_active = FALSE,
            token_revocation_version = $3, deleted_at = now(), updated_at = now()
        WHERE id = $1
        "#,
    )
    .bind(user_id)
    .bind(format!("deleted:{user_id}"))
    .bind(new_version)
    .execute(&mut *tx)
    .await?;

    sqlx::query(
        "UPDATE identity.refresh_tokens SET revoked = TRUE WHERE user_id = $1 AND revoked = FALSE",
    )
    .bind(user_id)
    .execute(&mut *tx)
    .await?;

    tx.commit().await?;
    tracing::info!(new_version, "account erased (soft-delete + PII redaction)");
    Ok(new_version)
}

/// The user's own identity record for a PDPA data export (§19/§32) — the data subject
/// reading THEIR OWN data, so real (un-redacted) values. Scoped strictly to `user_id`.
pub async fn export_user(db: &PgPool, user_id: Uuid) -> Result<serde_json::Value, AppError> {
    #[allow(clippy::type_complexity)]
    let row: Option<(
        String,
        Option<String>,
        String,
        bool,
        Option<DateTime<Utc>>,
        DateTime<Utc>,
        DateTime<Utc>,
    )> = sqlx::query_as(
        r#"
        SELECT phone, email, role::text AS role, is_active, deleted_at, created_at, updated_at
        FROM identity.users WHERE id = $1
        "#,
    )
    .bind(user_id)
    .fetch_optional(db)
    .await?;
    let (phone, email, role, is_active, deleted_at, created_at, updated_at) =
        row.ok_or_else(|| AppError::NotFound("User not found".to_string()))?;
    Ok(serde_json::json!({
        "user_id": user_id,
        "phone": phone,
        "email": email,
        "role": role,
        "is_active": is_active,
        "deleted_at": deleted_at,
        "created_at": created_at,
        "updated_at": updated_at,
    }))
}

#[cfg(test)]
mod tests {
    use super::*;
    // Used by the auth-hardening regression tests at the bottom of this module.
    use crate::domain::rotation::{decide, RotationDecision};
    use crate::domain::token;
    use std::sync::Arc;
    use tokio::sync::Barrier;

    #[test]
    fn dummy_hash_is_valid_and_never_matches() {
        // Anti-enumeration: the dummy must be a parseable PHC string so the no-such-user
        // path returns Ok(false) → generic 401, never Err → 500 (a timing oracle).
        assert!(
            matches!(
                password::verify_secret("any-password", DUMMY_HASH.as_str()),
                Ok(false)
            ),
            "DUMMY_HASH must parse and reject all inputs"
        );
    }

    /// DB-gated PDPA §33 erasure proof: a user can log in, then after `soft_delete_and_redact`
    /// the original credentials fail (deactivated + phone redacted), the row's PII is gone,
    /// and a second erase is a no-op NotFound (idempotent). Gated on `DATABASE_URL` (migrated
    /// identity 0001+0002); hermetic SKIP otherwise.
    #[tokio::test]
    async fn erasure_redacts_pii_and_blocks_login() {
        let Ok(db_url) = std::env::var("DATABASE_URL") else {
            eprintln!("SKIP: DATABASE_URL required for the erasure test");
            return;
        };
        let pool = sqlx::postgres::PgPoolOptions::new()
            .acquire_timeout(std::time::Duration::from_secs(5))
            .connect(&db_url)
            .await
            .expect("connect real Postgres");

        let user_id = Uuid::new_v4();
        let phone = format!("+66{}", &user_id.simple().to_string()[..9]);
        let pw_hash = password::hash_secret("secret123").expect("hash");
        // Seed an APPROVED account — login (verify_credentials) gates on approval_status,
        // and this test needs the credentials to be valid before erasure.
        sqlx::query(
            "INSERT INTO identity.users (id, phone, password_hash, role, approval_status) \
             VALUES ($1, $2, $3, 'customer', 'approved'::identity.approval_status)",
        )
        .bind(user_id)
        .bind(&phone)
        .bind(&pw_hash)
        .execute(&pool)
        .await
        .expect("seed user");

        // Logs in before erasure.
        assert!(
            verify_credentials(&pool, &phone, "secret123").await.is_ok(),
            "credentials valid before erasure"
        );

        // Erase.
        soft_delete_and_redact(&pool, user_id).await.expect("erase");

        // Original credentials no longer work (deactivated + phone redacted).
        assert!(
            verify_credentials(&pool, &phone, "secret123")
                .await
                .is_err(),
            "login blocked after erasure"
        );

        // PII redacted + deletion stamped.
        let (redacted_phone, email, is_active, deleted_at): (
            String,
            Option<String>,
            bool,
            Option<DateTime<Utc>>,
        ) = sqlx::query_as(
            "SELECT phone, email, is_active, deleted_at FROM identity.users WHERE id = $1",
        )
        .bind(user_id)
        .fetch_one(&pool)
        .await
        .expect("read redacted row");
        assert!(redacted_phone.starts_with("deleted:"), "phone redacted");
        assert!(email.is_none(), "email cleared");
        assert!(!is_active, "deactivated");
        assert!(deleted_at.is_some(), "deletion timestamp stamped");

        // Idempotent: a second erase finds nothing to do.
        assert!(
            soft_delete_and_redact(&pool, user_id).await.is_err(),
            "second erase is NotFound (idempotent)"
        );

        let _ = sqlx::query("DELETE FROM identity.users WHERE id = $1")
            .bind(user_id)
            .execute(&pool)
            .await;
    }

    /// DB-gated registration lifecycle: `upsert_pending_user` creates a PENDING (non-loginable)
    /// account; login is blocked while pending and allowed after approval; a re-register of a
    /// STILL-pending phone is allowed (refreshes credentials/role); a re-register of an
    /// APPROVED phone is rejected with `Conflict`. Gated on `DATABASE_URL` (identity 0001+0003).
    #[tokio::test]
    async fn registration_lifecycle_pending_then_approved() {
        let Ok(db_url) = std::env::var("DATABASE_URL") else {
            eprintln!("SKIP: DATABASE_URL required for the registration test");
            return;
        };
        let pool = sqlx::postgres::PgPoolOptions::new()
            .acquire_timeout(std::time::Duration::from_secs(5))
            .connect(&db_url)
            .await
            .expect("connect real Postgres");

        // A unique 10-digit Thai-format phone derived from a fresh UUID (digits only).
        let phone: String = format!(
            "0{}",
            &Uuid::new_v4()
                .simple()
                .to_string()
                .chars()
                .filter(|c| c.is_ascii_digit())
                .take(9)
                .collect::<String>()
        );
        // pin_hash = the 64-hex SHA-256 the mobile client sends; identity Argon2's it.
        let pin_hash = "a".repeat(64);

        // 1) Register → creates a pending account, returns a user_id.
        let user_id = upsert_pending_user(&pool, &phone, "guard", &pin_hash)
            .await
            .expect("register");

        // The row exists and is pending.
        let (status, role): (String, String) = sqlx::query_as(
            "SELECT approval_status::text, role::text FROM identity.users WHERE id = $1",
        )
        .bind(user_id)
        .fetch_one(&pool)
        .await
        .expect("read row");
        assert_eq!(status, "pending", "register creates a pending account");
        assert_eq!(role, "guard");

        // 2) Login is BLOCKED while pending (generic 401), even with the correct password.
        assert!(
            verify_credentials(&pool, &phone, &pin_hash).await.is_err(),
            "a pending account cannot log in"
        );

        // 3) Re-register the STILL-pending phone → allowed (refreshes creds, stays pending).
        let again = upsert_pending_user(&pool, &phone, "customer", &pin_hash)
            .await
            .expect("re-register pending");
        assert_eq!(
            again, user_id,
            "re-register hits the same row (ON CONFLICT)"
        );
        let (role2,): (String,) =
            sqlx::query_as("SELECT role::text FROM identity.users WHERE id = $1")
                .bind(user_id)
                .fetch_one(&pool)
                .await
                .expect("read role");
        assert_eq!(role2, "customer", "re-register may change the pending role");

        // 4) Approve → login now succeeds with the same credentials.
        sqlx::query(
            "UPDATE identity.users SET approval_status = 'approved'::identity.approval_status WHERE id = $1",
        )
        .bind(user_id)
        .execute(&pool)
        .await
        .expect("approve");
        let logged_in = verify_credentials(&pool, &phone, &pin_hash)
            .await
            .expect("login after approval");
        assert_eq!(logged_in.id, user_id);

        // 5) Re-register an APPROVED phone → Conflict (must log in instead).
        let err = upsert_pending_user(&pool, &phone, "guard", &pin_hash)
            .await
            .expect_err("re-register approved is a conflict");
        assert!(matches!(err, AppError::Conflict(_)), "got {err:?}");

        let _ = sqlx::query("DELETE FROM identity.users WHERE id = $1")
            .bind(user_id)
            .execute(&pool)
            .await;
    }

    /// DB-gated consumer idempotency: `approve_user_on_event` flips a pending account to
    /// `approved` AND records the `event_id`; a redelivery of the SAME event_id is a no-op
    /// (`Duplicate`); an event for an unknown user records the id but reports `UserNotFound`.
    /// Gated on `DATABASE_URL` (identity 0001+0003+0004).
    #[tokio::test]
    async fn approve_user_on_event_flips_and_is_idempotent() {
        let Ok(db_url) = std::env::var("DATABASE_URL") else {
            eprintln!("SKIP: DATABASE_URL required for the approval-consumer test");
            return;
        };
        let pool = sqlx::postgres::PgPoolOptions::new()
            .acquire_timeout(std::time::Duration::from_secs(5))
            .connect(&db_url)
            .await
            .expect("connect real Postgres");

        // Seed a PENDING guard (as register would).
        let user_id = Uuid::new_v4();
        let phone = format!("0{}", &user_id.simple().to_string()[..9]);
        let pw = password::hash_secret("x").expect("hash");
        sqlx::query(
            "INSERT INTO identity.users (id, phone, password_hash, role, approval_status) \
             VALUES ($1, $2, $3, 'guard', 'pending'::identity.approval_status)",
        )
        .bind(user_id)
        .bind(&phone)
        .bind(&pw)
        .execute(&pool)
        .await
        .expect("seed pending user");

        let event_id = Uuid::new_v4();
        let topic = "pguard.events.user.approved";

        // 1) First delivery → Applied; the column flips to approved.
        let outcome = approve_user_on_event(&pool, event_id, topic, user_id)
            .await
            .expect("apply");
        assert_eq!(outcome, ApprovedOutcome::Applied);
        let (status,): (String,) =
            sqlx::query_as("SELECT approval_status::text FROM identity.users WHERE id = $1")
                .bind(user_id)
                .fetch_one(&pool)
                .await
                .expect("read status");
        assert_eq!(status, "approved", "consumer flips approval_status");

        // 2) Redelivery of the SAME event_id → Duplicate (idempotent no-op).
        let again = approve_user_on_event(&pool, event_id, topic, user_id)
            .await
            .expect("redeliver");
        assert_eq!(again, ApprovedOutcome::Duplicate);

        // 3) A different event for an unknown user → UserNotFound (id still recorded).
        let outcome = approve_user_on_event(&pool, Uuid::new_v4(), topic, Uuid::new_v4())
            .await
            .expect("unknown user");
        assert_eq!(outcome, ApprovedOutcome::UserNotFound);

        // cleanup
        let _ = sqlx::query("DELETE FROM identity.processed_events WHERE event_id = $1")
            .bind(event_id)
            .execute(&pool)
            .await;
        let _ = sqlx::query("DELETE FROM identity.users WHERE id = $1")
            .bind(user_id)
            .execute(&pool)
            .await;
    }

    // ─────────────────────────────────────────────────────────────────────────────
    // Auth-hardening regression net (PR #37 shipped H1/H2 with no tests). All DB-gated on
    // DATABASE_URL (migrated identity 0001+); hermetic SKIP otherwise. refresh_tokens has no FK
    // to users, so these seed token rows directly with a random user_id (no user needed).
    //
    // COVERAGE NOTE (recorded follow-up): these lock the rotation DECISION + the repo primitives
    // (rotate/revoke_family/find). They do NOT drive the `refresh()` HTTP handler's match arms
    // end-to-end (ReuseDetected → revoke_family, CeilingExceeded → generic 401), because that
    // handler takes the concrete `AppState` (which mandates a live Redis the refresh path never
    // uses) rather than a lightweight deps seam like revoke-all/register. A handler-level
    // wiring test is a follow-up for the next auth slice (would need a Redis-backed AppState or a
    // `RefreshDeps` seam — both out of scope for a test-only slice). The arms are correct today.
    // ─────────────────────────────────────────────────────────────────────────────

    /// Connect a real pool (≥2 conns so the race tasks run truly concurrently), or `None` to SKIP.
    async fn gated_pool() -> Option<PgPool> {
        let db_url = std::env::var("DATABASE_URL").ok()?;
        Some(
            sqlx::postgres::PgPoolOptions::new()
                .max_connections(8)
                .acquire_timeout(std::time::Duration::from_secs(5))
                .connect(&db_url)
                .await
                .expect("connect real Postgres"),
        )
    }

    /// (rotation_id, family_id) for a freshly-minted opaque token.
    async fn ids_of(pool: &PgPool, opaque: &str) -> (Uuid, Uuid) {
        let (rid, _secret) = token::parse(opaque).expect("parse opaque token");
        let loc = find_refresh_by_rotation(pool, rid)
            .await
            .expect("find")
            .expect("row exists");
        (rid, loc.family_id)
    }

    async fn live_family_count(pool: &PgPool, user_id: Uuid) -> i64 {
        let (n,): (i64,) = sqlx::query_as(
            "SELECT count(DISTINCT family_id) FROM identity.refresh_tokens \
             WHERE user_id = $1 AND revoked = FALSE",
        )
        .bind(user_id)
        .fetch_one(pool)
        .await
        .expect("count live families");
        n
    }

    async fn live_tokens_in_family(pool: &PgPool, family_id: Uuid) -> i64 {
        let (n,): (i64,) = sqlx::query_as(
            "SELECT count(*) FROM identity.refresh_tokens WHERE family_id = $1 AND revoked = FALSE",
        )
        .bind(family_id)
        .fetch_one(pool)
        .await
        .expect("count live tokens");
        n
    }

    async fn cleanup_user(pool: &PgPool, user_id: Uuid) {
        let _ = sqlx::query("DELETE FROM identity.refresh_tokens WHERE user_id = $1")
            .bind(user_id)
            .execute(pool)
            .await;
    }

    /// H1 — concurrent refresh of the SAME token mints EXACTLY ONE successor (no double-spend), and
    /// the loser is rejected (Ok(None)) WITHOUT killing the family (a benign double-fire ≠ reuse).
    /// Looped to shake out scheduling flake; the conditional UPDATE + row lock make the outcome
    /// deterministic, not probabilistic, so this is a real race, not a sequential fake.
    ///
    /// NOTE: even if the two tasks happen to SERIALIZE (no true overlap), the assertion still holds
    /// and is still meaningful — the conditional `UPDATE … WHERE revoked = FALSE` guarantees
    /// exactly-one in either ordering. Do NOT "strengthen" this with timing assumptions; that would
    /// only make it flaky without testing anything more.
    #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
    async fn concurrent_rotation_mints_exactly_one_successor() {
        let Some(pool) = gated_pool().await else {
            eprintln!("SKIP: DATABASE_URL required for the concurrent-rotation race test");
            return;
        };
        let user_id = Uuid::new_v4();

        for i in 0..20 {
            let opaque = create_refresh_family(&pool, user_id).await.expect("login");
            let (rotation_id, family_id) = ids_of(&pool, &opaque).await;

            // Two tasks rotate the very same rotation_id, released together by a barrier.
            let barrier = Arc::new(Barrier::new(2));
            let spawn_one = || {
                let p = pool.clone();
                let b = barrier.clone();
                tokio::spawn(async move {
                    b.wait().await;
                    rotate(&p, user_id, family_id, rotation_id).await
                })
            };
            let (a, b) = tokio::join!(spawn_one(), spawn_one());
            let a = a.expect("task a joined").expect("rotate a ok");
            let b = b.expect("task b joined").expect("rotate b ok");

            // Exactly one successor; never two live chains from one token.
            assert!(
                a.is_some() != b.is_some(),
                "iter {i}: exactly one rotate must win (got a={}, b={})",
                a.is_some(),
                b.is_some()
            );
            // The family is NOT revoked: the winner's successor is the lone live token.
            assert_eq!(
                live_tokens_in_family(&pool, family_id).await,
                1,
                "iter {i}: race loser must not revoke the family (winner's successor stays live)"
            );
            // The winner's returned token resolves to exactly that lone live row (no stale/dup id).
            let winner = a.or(b).expect("a winner exists");
            let (winner_rid, _) = token::parse(&winner).expect("parse winner");
            let winner_row = find_refresh_by_rotation(&pool, winner_rid)
                .await
                .expect("find winner")
                .expect("winner row exists");
            assert!(
                !winner_row.stored.revoked,
                "iter {i}: the winner's token is live"
            );
            assert_eq!(
                winner_row.family_id, family_id,
                "iter {i}: successor stays in the family"
            );
        }

        cleanup_user(&pool, user_id).await;
    }

    /// H1 — sequential REUSE of a spent token is detected and kills the WHOLE family. Locks the
    /// chain the conditional UPDATE underpins: spend marks the row revoked → a replay is seen as
    /// revoked → `decide` returns ReuseDetected → the handler revokes the family (incl. the live
    /// successor). Breaking the `WHERE revoked = FALSE` guard would silently break this.
    #[tokio::test]
    async fn sequential_reuse_revokes_whole_family() {
        let Some(pool) = gated_pool().await else {
            eprintln!("SKIP: DATABASE_URL required for the sequential-reuse test");
            return;
        };
        let user_id = Uuid::new_v4();
        let opaque = create_refresh_family(&pool, user_id).await.expect("login");
        let (rotation_id, family_id) = ids_of(&pool, &opaque).await;

        // First use: live → Rotate → a successor is minted (the family now has a live token).
        let loc = find_refresh_by_rotation(&pool, rotation_id)
            .await
            .expect("find")
            .expect("row");
        assert_eq!(decide(&loc.stored, Utc::now()), RotationDecision::Rotate);
        let successor = rotate(&pool, user_id, family_id, rotation_id)
            .await
            .expect("rotate")
            .expect("successor minted");
        assert_eq!(live_tokens_in_family(&pool, family_id).await, 1);

        // Replay the now-spent rotation_id: it must read as revoked → ReuseDetected.
        let replayed = find_refresh_by_rotation(&pool, rotation_id)
            .await
            .expect("find")
            .expect("row");
        assert_eq!(
            decide(&replayed.stored, Utc::now()),
            RotationDecision::ReuseDetected,
            "a spent token must be marked revoked so replay is detected (guards the conditional UPDATE)"
        );

        // The reuse handler kills the family — including the live successor.
        revoke_family(&pool, family_id)
            .await
            .expect("revoke family");
        assert_eq!(
            live_tokens_in_family(&pool, family_id).await,
            0,
            "reuse detection must revoke the entire family"
        );
        // The successor is now dead too: presenting it reads as revoked (would be ReuseDetected).
        let (succ_rid, _) = token::parse(&successor).expect("parse successor");
        let succ = find_refresh_by_rotation(&pool, succ_rid)
            .await
            .expect("find")
            .expect("row");
        assert!(
            succ.stored.revoked,
            "the family-kill revoked the live successor too"
        );

        cleanup_user(&pool, user_id).await;
    }

    /// H2 — the per-user session cap evicts the LEAST-recently-active family (LRU) rather than
    /// rejecting the new login, and the surviving families remain usable.
    #[tokio::test]
    async fn session_cap_evicts_oldest_family_lru() {
        let Some(pool) = gated_pool().await else {
            eprintln!("SKIP: DATABASE_URL required for the session-cap test");
            return;
        };
        let user_id = Uuid::new_v4();

        // Create the cap's worth of families (MAX_SESSIONS_PER_USER = 5) and backdate each to a
        // DISTINCT created_at so the LRU order is deterministic (oldest = the first one).
        let mut fams: Vec<(Uuid, Uuid)> = Vec::new(); // (rotation_id, family_id)
        for i in 0..MAX_SESSIONS_PER_USER {
            let opaque = create_refresh_family(&pool, user_id).await.expect("login");
            let (rid, fid) = ids_of(&pool, &opaque).await;
            // family 0 oldest … family 4 newest (minutes ago: 50,40,30,20,10).
            let mins_ago = (MAX_SESSIONS_PER_USER - i) as i32 * 10;
            sqlx::query(
                "UPDATE identity.refresh_tokens SET created_at = now() - make_interval(mins => $2) \
                 WHERE family_id = $1",
            )
            .bind(fid)
            .bind(mins_ago)
            .execute(&pool)
            .await
            .expect("backdate family");
            fams.push((rid, fid));
        }
        assert_eq!(
            live_family_count(&pool, user_id).await,
            MAX_SESSIONS_PER_USER,
            "all {MAX_SESSIONS_PER_USER} families live before the cap-breaking login"
        );

        // The cap+1'th login: evict the oldest (fams[0]), keep the rest, add the new one.
        let new_opaque = create_refresh_family(&pool, user_id)
            .await
            .expect("cap+1 login");
        let (_new_rid, new_fid) = ids_of(&pool, &new_opaque).await;

        assert_eq!(
            live_family_count(&pool, user_id).await,
            MAX_SESSIONS_PER_USER,
            "login is NOT rejected at the cap — it evicts, holding the live count at the cap"
        );
        assert_eq!(
            live_tokens_in_family(&pool, fams[0].1).await,
            0,
            "the least-recently-active family is evicted (LRU)"
        );
        for (_, fid) in &fams[1..] {
            assert!(
                live_tokens_in_family(&pool, *fid).await > 0,
                "a more-recent family must survive eviction"
            );
        }
        assert!(
            live_tokens_in_family(&pool, new_fid).await > 0,
            "the new family is live"
        );

        // A surviving family is still usable (rotates successfully).
        let survivor_rid = fams[1].0;
        let survivor_fid = fams[1].1;
        assert!(
            rotate(&pool, user_id, survivor_fid, survivor_rid)
                .await
                .expect("rotate survivor")
                .is_some(),
            "a surviving family must still rotate"
        );

        cleanup_user(&pool, user_id).await;
    }

    /// H2 — a family that started rotating more than FAMILY_MAX_DAYS ago is rejected by the ceiling
    /// with a GENERIC outcome (CeilingExceeded → 401), and is NOT mis-classified as reuse: the
    /// token/family stay live (the ceiling is benign re-login, not a kill).
    #[tokio::test]
    async fn family_past_ceiling_rejected_without_kill() {
        let Some(pool) = gated_pool().await else {
            eprintln!("SKIP: DATABASE_URL required for the rotation-ceiling test");
            return;
        };
        let user_id = Uuid::new_v4();
        let opaque = create_refresh_family(&pool, user_id).await.expect("login");
        let (rotation_id, family_id) = ids_of(&pool, &opaque).await;

        // Backdate the family's only row so family_started_at (MIN created_at) is past the ceiling.
        sqlx::query(
            "UPDATE identity.refresh_tokens SET created_at = now() - interval '31 days' \
             WHERE family_id = $1",
        )
        .bind(family_id)
        .execute(&pool)
        .await
        .expect("backdate family start");

        let loc = find_refresh_by_rotation(&pool, rotation_id)
            .await
            .expect("find")
            .expect("row");
        assert_eq!(
            decide(&loc.stored, Utc::now()),
            RotationDecision::CeilingExceeded,
            "family older than FAMILY_MAX_DAYS hits the ceiling"
        );
        // Benign: the token is NOT revoked, the family is NOT killed (wrong-type-revoke guard).
        assert!(
            !loc.stored.revoked,
            "ceiling must not mark the token revoked"
        );
        assert_eq!(
            live_tokens_in_family(&pool, family_id).await,
            1,
            "ceiling is force-relogin, not a family revoke"
        );

        cleanup_user(&pool, user_id).await;
    }

    /// H2 edge — `family_started_at` is `MIN(created_at)` across ALL rows in the family, so a family
    /// that has rotated many times (newest token is fresh) still hits the ceiling on its true age.
    #[tokio::test]
    async fn family_started_at_is_min_across_all_rotations() {
        let Some(pool) = gated_pool().await else {
            eprintln!("SKIP: DATABASE_URL required for the family-age MIN edge test");
            return;
        };
        let user_id = Uuid::new_v4();
        let opaque = create_refresh_family(&pool, user_id).await.expect("login");
        let (rid0, family_id) = ids_of(&pool, &opaque).await;

        // Rotate twice → 3 rows in the family (rid0, rid1 revoked; rid2 live, freshly created).
        let t1 = rotate(&pool, user_id, family_id, rid0)
            .await
            .expect("rotate 1")
            .expect("successor 1");
        let (rid1, _) = token::parse(&t1).expect("parse t1");
        let t2 = rotate(&pool, user_id, family_id, rid1)
            .await
            .expect("rotate 2")
            .expect("successor 2");
        let (rid2, _) = token::parse(&t2).expect("parse t2");

        // Backdate ONLY the OLDEST row past the ceiling; the live token (rid2) is brand-new.
        sqlx::query(
            "UPDATE identity.refresh_tokens SET created_at = now() - interval '31 days' \
             WHERE rotation_id = $1",
        )
        .bind(rid0)
        .execute(&pool)
        .await
        .expect("backdate oldest row");

        let live = find_refresh_by_rotation(&pool, rid2)
            .await
            .expect("find")
            .expect("row");
        assert_eq!(
            decide(&live.stored, Utc::now()),
            RotationDecision::CeilingExceeded,
            "the family's age is MIN(created_at) across every row — a fresh newest token can't escape it"
        );

        cleanup_user(&pool, user_id).await;
    }
}
