// GENERATED by apps/design-tokens/extract.mjs from source/tokens.css — DO NOT EDIT.
// Full token set extracted from the hi-fi design (redesign-pguard tokens.css snapshot).
// Every member of the old placeholder keeps its NAME and VALUE (additive superset),
// so existing apps/mobile usage is source-compatible. Canonical import:
//   import 'package:pguard_design_tokens/pguard_design_tokens.dart';
import 'dart:ui' show Color;

/// pguard design tokens (LIGHT theme values + theme-independent scales).
class PgTokens {
  PgTokens._();

  static const Color colorGreen50 = Color(0xFFE9F8F1); // --green-50
  static const Color colorGreen100 = Color(0xFFC9EEDD); // --green-100
  static const Color colorGreen200 = Color(0xFF97E0C2); // --green-200
  static const Color colorGreen300 = Color(0xFF5FCEA4); // --green-300
  static const Color colorGreen400 = Color(0xFF30B987); // --green-400
  static const Color colorGreen500 = Color(0xFF1FA971); // --green-500
  static const Color colorGreen600 = Color(0xFF15885B); // --green-600
  static const Color colorGreen700 = Color(0xFF126B49); // --green-700
  static const Color colorGreen800 = Color(0xFF0E5238); // --green-800
  static const Color colorGreen900 = Color(0xFF0E3B2E); // --green-900
  static const Color colorGreen950 = Color(0xFF082619); // --green-950
  static const Color colorAmber50 = Color(0xFFFEF6E7); // --amber-50
  static const Color colorAmber100 = Color(0xFFFDE9C2); // --amber-100
  static const Color colorAmber200 = Color(0xFFFBD489); // --amber-200
  static const Color colorAmber300 = Color(0xFFF9BC4D); // --amber-300
  static const Color colorAmber400 = Color(0xFFF7A823); // --amber-400
  static const Color colorAmber500 = Color(0xFFF59E0B); // --amber-500
  static const Color colorAmber600 = Color(0xFFD97D06); // --amber-600
  static const Color colorAmber700 = Color(0xFFB45F09); // --amber-700
  static const Color colorAmber800 = Color(0xFF92490E); // --amber-800
  static const Color colorAmber900 = Color(0xFF78400F); // --amber-900
  static const Color colorN0 = Color(0xFFFFFFFF); // --n-0
  static const Color colorN50 = Color(0xFFF6F8F7); // --n-50
  static const Color colorN100 = Color(0xFFEDF1EF); // --n-100
  static const Color colorN200 = Color(0xFFDEE5E2); // --n-200
  static const Color colorN300 = Color(0xFFC6D0CC); // --n-300
  static const Color colorN400 = Color(0xFF94A29D); // --n-400
  static const Color colorN500 = Color(0xFF69776F); // --n-500
  static const Color colorN600 = Color(0xFF4C5953); // --n-600
  static const Color colorN700 = Color(0xFF36423D); // --n-700
  static const Color colorN800 = Color(0xFF222B27); // --n-800
  static const Color colorN900 = Color(0xFF141A17); // --n-900
  static const Color colorN950 = Color(0xFF0A0E0C); // --n-950
  static const Color colorSuccess = Color(0xFF16A34A); // --success
  static const Color colorSuccessBg = Color(0xFFE7F6ED); // --success-bg
  static const Color colorWarning = Color(0xFFF59E0B); // --warning
  static const Color colorWarningBg = Color(0xFFFEF3E0); // --warning-bg
  static const Color colorDanger = Color(0xFFE5484D); // --danger
  static const Color colorDangerBg = Color(0xFFFCEAEA); // --danger-bg
  static const Color colorInfo = Color(0xFF2A6FDB); // --info
  static const Color colorInfoBg = Color(0xFFE8F0FC); // --info-bg
  static const Color colorStatusActive = Color(0xFF1FA971); // --status-active
  static const Color colorStatusWorking = Color(0xFFF59E0B); // --status-working
  static const Color colorStatusOffline = Color(0xFFEF5C5C); // --status-offline
  static const Color colorStatusActiveRing = Color(0x381FA971); // --status-active-ring
  static const Color colorStatusWorkingRing = Color(0x38F59E0B); // --status-working-ring
  static const Color colorStatusOfflineRing = Color(0x33EF5C5C); // --status-offline-ring
  static const Color colorBg = Color(0xFFF6F8F7); // --bg-app
  static const Color colorSurface = Color(0xFFFFFFFF); // --bg-surface
  static const Color colorRaised = Color(0xFFFFFFFF); // --bg-raised
  static const Color colorSunken = Color(0xFFEDF1EF); // --bg-sunken
  static const Color colorInverse = Color(0xFF0E3B2E); // --bg-inverse
  static const Color colorBorder = Color(0xFFDEE5E2); // --border
  static const Color colorBorderStrong = Color(0xFFC6D0CC); // --border-strong
  static const Color colorTextStrong = Color(0xFF141A17); // --text-strong
  static const Color colorText = Color(0xFF222B27); // --text
  static const Color colorTextMuted = Color(0xFF69776F); // --text-muted
  static const Color colorTextFaint = Color(0xFF94A29D); // --text-faint
  static const Color colorTextOnBrand = Color(0xFFFFFFFF); // --text-on-brand
  static const Color colorBrand = Color(0xFF0E3B2E); // --brand
  static const Color colorPrimary = Color(0xFF1FA971); // --brand-int
  static const Color colorPrimaryHover = Color(0xFF15885B); // --brand-int-hover
  static const Color colorAccent = Color(0xFFF59E0B); // --accent
  static const Color colorAccentHover = Color(0xFFD97D06); // --accent-hover
  static const Color colorFocusRing = Color(0x731FA971); // --focus-ring
  static const Color colorOnAmber = Color(0xFF2A1500); // admin.css .btn.accent text

  static const double fontSizeDisplay = 44; // --t-display
  static const double fontSizeH1 = 34; // --t-h1
  static const double fontSizeH2 = 27; // --t-h2
  static const double fontSizeH3 = 21; // --t-h3
  static const double fontSizeLg = 18; // --t-lg
  static const double fontSizeBase = 16; // --t-base
  static const double fontSizeSm = 14; // --t-sm
  static const double fontSizeXs = 12; // --t-xs
  static const double fontSize2xs = 11; // --t-2xs
  static const double lineHeightTight = 1.3; // --lh-tight
  static const double lineHeightSnug = 1.45; // --lh-snug
  static const double lineHeightBase = 1.62; // --lh-base
  static const double lineHeightRelaxed = 1.78; // --lh-relaxed
  static const double space1 = 4; // --sp-1
  static const double space2 = 8; // --sp-2
  static const double space3 = 12; // --sp-3
  static const double space4 = 16; // --sp-4
  static const double space5 = 20; // --sp-5
  static const double space6 = 24; // --sp-6
  static const double space7 = 32; // --sp-7
  static const double space8 = 40; // --sp-8
  static const double space9 = 48; // --sp-9
  static const double space10 = 64; // --sp-10
  static const double space11 = 80; // --sp-11
  static const double space12 = 96; // --sp-12
  static const double radiusXs = 4; // --r-xs
  static const double radiusSm = 6; // --r-sm
  static const double radiusMd = 8; // --r-md
  static const double radiusLg = 11; // --r-lg
  static const double radiusXl = 14; // --r-xl
  static const double radius2xl = 18; // --r-2xl
  static const double radiusFull = 999; // --r-full
  static const double tapTarget = 44; // --tap

  static const String fontFamilyThai = 'IBM Plex Sans Thai'; // --font-thai (primary)
  static const String fontFamilyLatin = 'IBM Plex Sans'; // --font-latin (primary)
  static const String fontFamilyMono = 'IBM Plex Mono'; // --font-mono (primary)
}

/// Dark-theme overrides (same member names as [PgTokens] where the design's
/// `[data-theme="dark"]` block overrides them; scales are theme-independent).
class PgTokensDark {
  PgTokensDark._();

  static const Color colorSuccessBg = Color(0x2916A34A); // --success-bg (dark)
  static const Color colorWarningBg = Color(0x26F59E0B); // --warning-bg (dark)
  static const Color colorDangerBg = Color(0x29E5484D); // --danger-bg (dark)
  static const Color colorInfoBg = Color(0x292A6FDB); // --info-bg (dark)
  static const Color colorBg = Color(0xFF0A0F0D); // --bg-app (dark)
  static const Color colorSurface = Color(0xFF121916); // --bg-surface (dark)
  static const Color colorRaised = Color(0xFF18211D); // --bg-raised (dark)
  static const Color colorSunken = Color(0xFF0D1411); // --bg-sunken (dark)
  static const Color colorInverse = Color(0xFFE9F8F1); // --bg-inverse (dark)
  static const Color colorBorder = Color(0xFF243029); // --border (dark)
  static const Color colorBorderStrong = Color(0xFF324239); // --border-strong (dark)
  static const Color colorTextStrong = Color(0xFFF3F7F5); // --text-strong (dark)
  static const Color colorText = Color(0xFFDCE5E0); // --text (dark)
  static const Color colorTextMuted = Color(0xFF93A29B); // --text-muted (dark)
  static const Color colorTextFaint = Color(0xFF6B7A72); // --text-faint (dark)
  static const Color colorTextOnBrand = Color(0xFF04140D); // --text-on-brand (dark)
  static const Color colorBrand = Color(0xFF0F2A21); // --brand (dark)
  static const Color colorPrimary = Color(0xFF2FC089); // --brand-int (dark)
  static const Color colorPrimaryHover = Color(0xFF45CF9A); // --brand-int-hover (dark)
  static const Color colorAccent = Color(0xFFFBB23E); // --accent (dark)
  static const Color colorAccentHover = Color(0xFFFFC560); // --accent-hover (dark)
  static const Color colorFocusRing = Color(0x802FC089); // --focus-ring (dark)
}
