#!/usr/bin/env python3
# pguard v2 — Rust event serde-type generator.
#
# Reads contracts/asyncapi/events.yaml and emits serde structs for every event PAYLOAD
# (the inner `payload` of the shared `EventEnvelope<T>`) into
# packages/shared-events/src/generated/events.rs.
#
# WHY a small in-repo generator (not typify / @asyncapi/generator):
#   - The envelope is already a hand-written GENERIC `EventEnvelope<T>` in shared-events; we only
#     need the 11 typed PAYLOADs, which live as the `payload` sub-schema inside each AsyncAPI
#     `EnvelopeOf_*` allOf. Extracting just those is a few lines here, vs. wrangling typify/asyncapi
#     tooling (Java/■ extra deps) to merge allOf and then un-merge the envelope.
#   - Reproducible on any CI runner: python3 + PyYAML only (no Java, no Docker). Pinned via
#     tooling/codegen/requirements.txt.
#   - Output is rustfmt-clean by construction (see generate.sh, which `cargo fmt --check`s it).
#
# Deterministic: schema + field order follow the YAML; struct name = the schema key minus the
# `EnvelopeOf_` prefix. Re-running on an unchanged contract produces byte-identical output (the
# CI stale-check relies on this).
import pathlib
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parents[2]
SPEC = ROOT / "contracts" / "asyncapi" / "events.yaml"
OUT = ROOT / "packages" / "shared-events" / "src" / "generated" / "events.rs"

PREFIX = "EnvelopeOf_"


def rust_type(prop):
    """Map a JSON-Schema leaf to a Rust type. Unknown shapes fail loudly (no silent Value)."""
    t = prop.get("type")
    fmt = prop.get("format")
    if t == "string":
        if fmt == "uuid":
            return "Uuid"
        if fmt == "date-time":
            return "DateTime<Utc>"
        return "String"
    if t == "integer":
        return "i64" if fmt == "int64" else "i32"
    if t == "number":
        return "f64"
    if t == "boolean":
        return "bool"
    raise SystemExit(f"gen_rust_events: unsupported schema leaf {prop!r} — extend rust_type()")


def payload_schema(env_schema):
    """The inner payload object schema from an `EnvelopeOf_*` allOf[Envelope, {payload}]."""
    for part in env_schema.get("allOf", []):
        props = part.get("properties")
        if props and "payload" in props:
            return props["payload"]
    raise SystemExit("gen_rust_events: an EnvelopeOf_* schema has no payload override")


def main():
    spec = yaml.safe_load(SPEC.read_text())
    schemas = spec["components"]["schemas"]
    structs = []  # (name, [(field, rust_type, optional)])
    needs_chrono = False
    for key, schema in schemas.items():
        if not key.startswith(PREFIX):
            continue
        name = key[len(PREFIX):]
        payload = payload_schema(schema)
        required = set(payload.get("required", []))
        fields = []
        for fname, prop in payload.get("properties", {}).items():
            ty = rust_type(prop)
            if ty == "DateTime<Utc>":
                needs_chrono = True
            fields.append((fname, ty, fname not in required))
        structs.append((name, fields))

    lines = []
    lines.append(
        "// @generated by tooling/codegen/gen_rust_events.py from contracts/asyncapi/events.yaml"
    )
    lines.append(
        "// DO NOT EDIT BY HAND — change the contract, then re-run ./tooling/codegen/generate.sh."
    )
    lines.append("//!")
    lines.append("//! Typed serde structs for every `pguard.events.*` PAYLOAD (the inner `payload`")
    lines.append("//! of [`crate::EventEnvelope`]). These are a CONTRACT-LOCK: the drift-lock tests")
    lines.append("//! (`tests/drift_lock.rs`) prove each one round-trips the exact JSON the services")
    lines.append("//! emit today, so editing events.yaml without regenerating turns the suite red.")
    lines.append("//! Services still build payloads inline today; adopting these is a follow-up.")
    lines.append("")
    # pub structs + fields are public API ⇒ no dead_code; but they are not yet *used* by any
    # binary in-workspace, so guard against an over-eager dead_code in the unused path.
    lines.append("#![allow(dead_code)]")
    lines.append("")
    if needs_chrono:
        lines.append("use chrono::{DateTime, Utc};")
    lines.append("use serde::{Deserialize, Serialize};")
    lines.append("use uuid::Uuid;")
    lines.append("")

    for i, (name, fields) in enumerate(structs):
        if i:
            lines.append("")
        lines.append("#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]")
        lines.append(f"pub struct {name} {{")
        for fname, ty, optional in fields:
            if optional:
                lines.append('    #[serde(default, skip_serializing_if = "Option::is_none")]')
                lines.append(f"    pub {fname}: Option<{ty}>,")
            else:
                lines.append(f"    pub {fname}: {ty},")
        lines.append("}")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")
    print(f"  -> {OUT.relative_to(ROOT)} ({len(structs)} payload structs)", file=sys.stderr)


if __name__ == "__main__":
    main()
