// GENERATED by apps/design-tokens/extract.mjs from source/tokens.css — DO NOT EDIT.
// Superset of the old placeholder: flat semantic keys keep their names + values; the
// ramps were RESTRUCTURED to nested objects (green50 → green["50"]) — no repo consumer
// existed at restructure time. The Dart output keeps every old member name (mobile uses it).

export const pgTokens = {
  color: {
    green: {
      "50": "#E9F8F1",
      "100": "#C9EEDD",
      "200": "#97E0C2",
      "300": "#5FCEA4",
      "400": "#30B987",
      "500": "#1FA971",
      "600": "#15885B",
      "700": "#126B49",
      "800": "#0E5238",
      "900": "#0E3B2E",
      "950": "#082619"
    },
    amber: {
      "50": "#FEF6E7",
      "100": "#FDE9C2",
      "200": "#FBD489",
      "300": "#F9BC4D",
      "400": "#F7A823",
      "500": "#F59E0B",
      "600": "#D97D06",
      "700": "#B45F09",
      "800": "#92490E",
      "900": "#78400F"
    },
    n: {
      "0": "#FFFFFF",
      "50": "#F6F8F7",
      "100": "#EDF1EF",
      "200": "#DEE5E2",
      "300": "#C6D0CC",
      "400": "#94A29D",
      "500": "#69776F",
      "600": "#4C5953",
      "700": "#36423D",
      "800": "#222B27",
      "900": "#141A17",
      "950": "#0A0E0C"
    },
    success: "#16A34A",
    successBg: "#E7F6ED",
    warning: "#F59E0B",
    warningBg: "#FEF3E0",
    danger: "#E5484D",
    dangerBg: "#FCEAEA",
    info: "#2A6FDB",
    infoBg: "#E8F0FC",
    statusActive: "#1FA971",
    statusWorking: "#F59E0B",
    statusOffline: "#EF5C5C",
    statusActiveRing: "rgba(31,169,113,.22)",
    statusWorkingRing: "rgba(245,158,11,.22)",
    statusOfflineRing: "rgba(239,92,92,.20)",
    bg: "#F6F8F7",
    surface: "#FFFFFF",
    raised: "#FFFFFF",
    sunken: "#EDF1EF",
    inverse: "#0E3B2E",
    border: "#DEE5E2",
    borderStrong: "#C6D0CC",
    textStrong: "#141A17",
    text: "#222B27",
    textMuted: "#69776F",
    textFaint: "#94A29D",
    textOnBrand: "#FFFFFF",
    brand: "#0E3B2E",
    primary: "#1FA971",
    primaryHover: "#15885B",
    accent: "#F59E0B",
    accentHover: "#D97D06",
    focusRing: "rgba(31,169,113,.45)",
    onAmber: "#2A1500"
  },
  text: {
    display: 44,
    h1: 34,
    h2: 27,
    h3: 21,
    lg: 18,
    base: 16,
    sm: 14,
    xs: 12,
    "2xs": 11
  },
  lineHeight: {
    tight: 1.3,
    snug: 1.45,
    base: 1.62,
    relaxed: 1.78
  },
  letterSpacing: {
    thai: "0.01em"
  },
  space: {
    "1": 4,
    "2": 8,
    "3": 12,
    "4": 16,
    "5": 20,
    "6": 24,
    "7": 32,
    "8": 40,
    "9": 48,
    "10": 64,
    "11": 80,
    "12": 96
  },
  radius: {
    xs: 4,
    sm: 6,
    md: 8,
    lg: 11,
    xl: 14,
    "2xl": 18,
    full: 999
  },
  tap: 44,
  font: {
    thai: "'IBM Plex Sans Thai', 'IBM Plex Sans', system-ui, sans-serif",
    latin: "'IBM Plex Sans', 'IBM Plex Sans Thai', system-ui, sans-serif",
    mono: "'IBM Plex Mono', ui-monospace, monospace"
  },
  shadow: {
    xs: "0 1px 1px rgba(8,38,25,.04)",
    sm: "0 1px 2px rgba(8,38,25,.06)",
    md: "0 2px 6px rgba(8,38,25,.07), 0 1px 2px rgba(8,38,25,.04)",
    lg: "0 8px 20px rgba(8,38,25,.10), 0 2px 5px rgba(8,38,25,.05)",
    xl: "0 18px 44px rgba(8,38,25,.15), 0 5px 12px rgba(8,38,25,.07)",
    brand: "0 6px 16px rgba(31,169,113,.22)",
    accent: "0 6px 16px rgba(245,158,11,.22)"
  },
  dark: {
    color: {
      successBg: "rgba(22,163,74,.16)",
      warningBg: "rgba(245,158,11,.15)",
      dangerBg: "rgba(229,72,77,.16)",
      infoBg: "rgba(42,111,219,.16)",
      bg: "#0A0F0D",
      surface: "#121916",
      raised: "#18211D",
      sunken: "#0D1411",
      inverse: "#E9F8F1",
      border: "#243029",
      borderStrong: "#324239",
      textStrong: "#F3F7F5",
      text: "#DCE5E0",
      textMuted: "#93A29B",
      textFaint: "#6B7A72",
      textOnBrand: "#04140D",
      brand: "#0F2A21",
      primary: "#2FC089",
      primaryHover: "#45CF9A",
      accent: "#FBB23E",
      accentHover: "#FFC560",
      focusRing: "rgba(47,192,137,.5)"
    },
    shadow: {
      xs: "0 1px 2px rgba(0,0,0,.4)",
      sm: "0 1px 3px rgba(0,0,0,.5), 0 1px 2px rgba(0,0,0,.4)",
      md: "0 4px 14px rgba(0,0,0,.5)",
      lg: "0 14px 32px rgba(0,0,0,.55)",
      xl: "0 26px 60px rgba(0,0,0,.6)"
    }
  }
} as const;

export type PgTokens = typeof pgTokens;
